#ifndef GAMEPAD_DEFINES_H_
#define GAMEPAD_DEFINES_H_

#define HA_CONTROLLER1 0
#define HA_CONTROLLER2 1
#define HA_CONTROLLER3 2
#define HA_CONTROLLER4 3

#define HA_GAMEPAD_UP 0
#define HA_GAMEPAD_DOWN 1
#define HA_GAMEPAD_LEFT 2
#define HA_GAMEPAD_RIGHT 3
#define HA_GAMEPAD_START 4
#define HA_GAMEPAD_BACK 5
#define HA_GAMEPAD_LEFT_THUMB 6
#define HA_GAMEPAD_RIGHT_THUMB 7
#define HA_GAMEPAD_LEFT_SHOULDER 8
#define HA_GAMEPAD_RIGHT_SHOULDER 9
#define HA_GAMEPAD_A 10
#define HA_GAMEPAD_B 11
#define HA_GAMEPAD_X 12
#define HA_GAMEPAD_Y 13

#endif
